//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILT_IN_ROOM
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TYPE_BUILT_IN_ROOM_ID { get; set; }
        public Nullable<decimal> TOTAL_AREA { get; set; }
        public Nullable<decimal> TYPE_FOUNDATION_ID { get; set; }
    
        public virtual TYPE_FOUNDATION TYPE_FOUNDATION { get; set; }
        public virtual SUB_OBJECT SUB_OBJECT { get; set; }
    }
}
