//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BUILT_IN_ROOM> BUILT_IN_ROOM { get; set; }
        public DbSet<CUSTOMER> CUSTOMER { get; set; }
        public DbSet<HOUSE> HOUSE { get; set; }
        public DbSet<MANAGEMENT> MANAGEMENT { get; set; }
        public DbSet<OBJECT_CONSTRUCTION> OBJECT_CONSTRUCTION { get; set; }
        public DbSet<QUALIFIER_OBJECT_CONSTRUCTION> QUALIFIER_OBJECT_CONSTRUCTION { get; set; }
        public DbSet<SUB_OBJECT> SUB_OBJECT { get; set; }
        public DbSet<TYPE_FOUNDATION> TYPE_FOUNDATION { get; set; }
        public DbSet<OBJECT_CONSTRUCTION_TREE> OBJECT_CONSTRUCTION_TREE { get; set; }
    
        [EdmFunction("Entities", "GET_ALL_SERIES_FOR_HOUSE")]
        public virtual IQueryable<GET_ALL_SERIES_FOR_HOUSE_Result> GET_ALL_SERIES_FOR_HOUSE(Nullable<decimal> hOUSE_ID)
        {
            var hOUSE_IDParameter = hOUSE_ID.HasValue ?
                new ObjectParameter("HOUSE_ID", hOUSE_ID) :
                new ObjectParameter("HOUSE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_ALL_SERIES_FOR_HOUSE_Result>("[Entities].[GET_ALL_SERIES_FOR_HOUSE](@HOUSE_ID)", hOUSE_IDParameter);
        }
    
        [EdmFunction("Entities", "GET_ALL_TYPE_SOUR_FIN")]
        public virtual IQueryable<GET_ALL_TYPE_SOUR_FIN_Result> GET_ALL_TYPE_SOUR_FIN(Nullable<decimal> sUB_OBJECT_ID)
        {
            var sUB_OBJECT_IDParameter = sUB_OBJECT_ID.HasValue ?
                new ObjectParameter("SUB_OBJECT_ID", sUB_OBJECT_ID) :
                new ObjectParameter("SUB_OBJECT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_ALL_TYPE_SOUR_FIN_Result>("[Entities].[GET_ALL_TYPE_SOUR_FIN](@SUB_OBJECT_ID)", sUB_OBJECT_IDParameter);
        }
    
        [EdmFunction("Entities", "GET_LAST_CONSTRACTION_TERM")]
        public virtual IQueryable<GET_LAST_CONSTRACTION_TERM_Result> GET_LAST_CONSTRACTION_TERM(Nullable<decimal> sUB_OBJECT_ID)
        {
            var sUB_OBJECT_IDParameter = sUB_OBJECT_ID.HasValue ?
                new ObjectParameter("SUB_OBJECT_ID", sUB_OBJECT_ID) :
                new ObjectParameter("SUB_OBJECT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_LAST_CONSTRACTION_TERM_Result>("[Entities].[GET_LAST_CONSTRACTION_TERM](@SUB_OBJECT_ID)", sUB_OBJECT_IDParameter);
        }
    
        [EdmFunction("Entities", "GET_LAST_PERMISSION_ICW")]
        public virtual IQueryable<GET_LAST_PERMISSION_ICW_Result> GET_LAST_PERMISSION_ICW(Nullable<decimal> sUB_OBJECT_ID)
        {
            var sUB_OBJECT_IDParameter = sUB_OBJECT_ID.HasValue ?
                new ObjectParameter("SUB_OBJECT_ID", sUB_OBJECT_ID) :
                new ObjectParameter("SUB_OBJECT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_LAST_PERMISSION_ICW_Result>("[Entities].[GET_LAST_PERMISSION_ICW](@SUB_OBJECT_ID)", sUB_OBJECT_IDParameter);
        }
    
        [EdmFunction("Entities", "GET_SUB_OBJECT_NAME")]
        public virtual IQueryable<GET_SUB_OBJECT_NAME_Result> GET_SUB_OBJECT_NAME(Nullable<decimal> sUB_OBJECT_ID)
        {
            var sUB_OBJECT_IDParameter = sUB_OBJECT_ID.HasValue ?
                new ObjectParameter("SUB_OBJECT_ID", sUB_OBJECT_ID) :
                new ObjectParameter("SUB_OBJECT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_SUB_OBJECT_NAME_Result>("[Entities].[GET_SUB_OBJECT_NAME](@SUB_OBJECT_ID)", sUB_OBJECT_IDParameter);
        }
    }
}
