//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOUSE
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> BEGINNING_TECHNICAL_BREAK { get; set; }
        public Nullable<System.DateTime> TERMINATION_TECHNICAL_BREAK { get; set; }
        public Nullable<decimal> MAX_COUNT_FLOORS { get; set; }
        public Nullable<decimal> COUNT_APARTMENTS { get; set; }
        public Nullable<decimal> TOTAL_AREA { get; set; }
        public Nullable<decimal> TYPE_FOUNDATION_ID { get; set; }
        public Nullable<System.DateTime> SETTLING_DATE { get; set; }
    
        public virtual SUB_OBJECT SUB_OBJECT { get; set; }
        public virtual TYPE_FOUNDATION TYPE_FOUNDATION { get; set; }
    }
}
