//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_CONSTRUCTION_TREE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PARENT_ID { get; set; }
        public string UNION_ID { get; set; }
        public string PARENT_UNION_ID { get; set; }
        public string NAME { get; set; }
        public decimal LVL { get; set; }
        public decimal NODE_TYPE_ID { get; set; }
        public string NODE_TYPE_NAME { get; set; }
        public decimal HAVE_CHILDS { get; set; }
    }
}
