//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALIFIER_OBJECT_CONSTRUCTION
    {
        public QUALIFIER_OBJECT_CONSTRUCTION()
        {
            this.QUALIFIER_OBJECT_CONSTRUCTION1 = new HashSet<QUALIFIER_OBJECT_CONSTRUCTION>();
            this.SUB_OBJECT = new HashSet<SUB_OBJECT>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> PARENT_QUALIFIER_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<QUALIFIER_OBJECT_CONSTRUCTION> QUALIFIER_OBJECT_CONSTRUCTION1 { get; set; }
        public virtual QUALIFIER_OBJECT_CONSTRUCTION QUALIFIER_OBJECT_CONSTRUCTION2 { get; set; }
        public virtual ICollection<SUB_OBJECT> SUB_OBJECT { get; set; }
    }
}
