//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_OBJECT
    {
        public decimal ID { get; set; }
        public decimal OBJECT_ID { get; set; }
        public string CODE { get; set; }
        public string CONSTRUCTION_NUMBER { get; set; }
        public Nullable<decimal> CONSTRUCTION_PERIOD { get; set; }
        public Nullable<decimal> ORDER_CONSTRUCTION_PERIOD { get; set; }
        public string PERM_IDKNS_NUMBER { get; set; }
        public Nullable<System.DateTime> PERM_BUILDING_SITE_DATE_RECEIPT { get; set; }
        public Nullable<System.DateTime> PERM_BUILDING_SITE_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> COMMISSIONIN_DATE { get; set; }
        public string COMMIS_DATE_COMMENT { get; set; }
        public decimal ALL_SCH_WORK_IS_COMPLETE { get; set; }
        public Nullable<decimal> COST_ALL_WORKS { get; set; }
        public Nullable<System.DateTime> COST_ALL_WORKS_PRICES_DATE { get; set; }
        public Nullable<decimal> TERM_PAY_EXEC_WORKS { get; set; }
        public Nullable<decimal> TYPE_DAYS_ID { get; set; }
        public Nullable<decimal> ADVANCE { get; set; }
        public decimal ADVANCE_PAYMENT_TO { get; set; }
        public decimal ADVANCE_PAYMENT_ICW { get; set; }
        public decimal PROTECTION_UPON { get; set; }
        public decimal TYPE_SUB_OBJECT_ID { get; set; }
        public decimal IS_ACTIVE { get; set; }
    
        public virtual BUILT_IN_ROOM BUILT_IN_ROOM { get; set; }
        public virtual HOUSE HOUSE { get; set; }
        public virtual OBJECT_CONSTRUCTION OBJECT_CONSTRUCTION { get; set; }
        public virtual QUALIFIER_OBJECT_CONSTRUCTION QUALIFIER_OBJECT_CONSTRUCTION { get; set; }
    }
}
